package 프로그래머스.Lv1.직사각형별찍기

import java.io.BufferedInputStream
import java.io.BufferedOutputStream

const val IBS = 1 shl 6
const val OBS = 1 shl 18
val O = BufferedOutputStream(System.out, OBS)
val I = BufferedInputStream(System.`in`)
val IB = ByteArray(IBS)
var Ii = 0
var Il = 0
const val EOF = -1

fun r(): Byte {
  if (Ii == Il) {
    Il = I.read(IB, 0, IBS)
    if (Il == EOF) IB[0] = EOF.toByte()
    Ii = 0
  }
  return IB[Ii++]
}

val NUM = 48..57
fun i(): Int {
  var v = 0
  var s = 1
  var b: Byte
  while (r().also { b = it } in NUM || b == 45.toByte()) {
    when (b) {
      in NUM -> v = v * 10 + b - 48
      else -> s = -1
    }
  }
  return s * v
}

val STAR: Byte = 42
val STARS = byteArrayOf(
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR,
  STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR, STAR
)

fun main(args: Array<String>) {
  val cols = i()
  val rows = i()
  repeat(rows) {
    O.write(STARS, 0, cols)
    O.write(10)
  }

  O.flush()
}

/**
 * ```
 * [ME]
 * 테스트 1 〉	통과 (58.11ms, 51.4MB)
 * 테스트 2 〉	통과 (54.09ms, 51.5MB)
 * 테스트 3 〉	통과 (65.27ms, 51.4MB)
 * 테스트 4 〉	통과 (57.82ms, 51.4MB)
 * 테스트 5 〉	통과 (54.55ms, 51.8MB)
 * 테스트 6 〉	통과 (55.92ms, 51.4MB)
 * 테스트 7 〉	통과 (63.00ms, 51MB)
 * ```
 *
 * ```
 * [RIVAL]
 * fun main(args: Array<String>) {
 *     val (a, b) = readLine()!!.split(' ').map(String::toInt)
 *     //println(a + b)
 *
 *     var star : String = ""
 *     for(i in 1..a){
 *         star += "*"
 *     }
 *
 *     for(i in 1..b){
 *         println(star)
 *     }
 *
 * }
 * 테스트 1 〉	통과 (72.76ms, 52.8MB)
 * 테스트 2 〉	통과 (97.31ms, 53.3MB)
 * 테스트 3 〉	통과 (69.82ms, 53.2MB)
 * 테스트 4 〉	통과 (73.42ms, 53MB)
 * 테스트 5 〉	통과 (64.45ms, 53.6MB)
 * 테스트 6 〉	통과 (70.07ms, 53.3MB)
 * 테스트 7 〉	통과 (78.83ms, 52.9MB)
 * ```
 */
